# Generated by Django 4.2.8 on 2023-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_producto_cantidad_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
